### PR TITLE
Denavit-Hartenberg convention added

### PR DESCRIPTION
**Pull request by tommy3001**
Here is a concept of the Denavit-Hartenberg convention for chains. 
[wikipedia](https://en.wikipedia.org/wiki/Denavit%E2%80%93Hartenberg_parameters)

### CODE REVIEW

**Comment by tommy3001** [comment]
Some documentation changes

**Comment by thomas-haslwanter** [comment]
Hi Tommy,
Thanks for the contribution!
Since I don't come from robotics, could you please send me a link about the Denavit-Hartenberg convention, so I can read up on it?
Also, it would be brilliant, if you could also add a test, to make sure the file does what you want it to do. (Just add a test-function to test_rotmat.py

Thanks!

**Comment by tommy3001** [comment]
Ok. 
I will add  tests and some further examples / documentation

**Comment by thomas-haslwanter** [comment]
Hmm, I had a quick look at the code:
if the DH-rotation matrix would be implemented like

```
R_dh = np.diag([0,0,0,1.])
R_dh[:-1,:-1] = skin.rotmat.R(axis,angle)
```
we could have the x- and the z-axis implemented with one function, and equivalently for the translation.
What do you think?

**Comment by thomas-haslwanter** [comment]
Or even better: A "spatial transformation matrix" could be implemented as

```
def stm(axis, angle, translation):
    """Spatial Transformation Matrix"""
    stm = np.diag([0,0,0,0.1])
    stm[:-1,:-1] = R(axis, angle)
    stm[:-1,:3] = translation
```

and the DH-rotation and translation matrices would only be special cases!

**Pull request merged**
